### ISSUE TITLE
integration with wechat public account

### ISSUE THREAD

**Issue by autratec** [smilexiaobao1992/Wechat_openai#2]
可以提供更详细的资料，以协助和 WECHAT 公众号的继承吗？ 具体问题如下：

1. 在公众号里，提供 开发者ID。 这个需要在程序中输入吗？
2. 服务器地址如何设定? 在 COLAB 环境里运行，是否可以和 NGROK 结合使用？ 将NGROK 生成的地址输入到 WECHAT 服务器地址中？有什么注意事项吗？
3. TOKEN 是自己定义的吗？ 在您的代码里，两次提到 TOKEN: app.config['your_api_secret'] = 'your_token'  # 将your_token替换为你的Token字符串,  # 替换为自己的Token字符串         token = app.config['b5728cf9ec6801dedf2ec929f5ff99ec'] 都是指WECHAT 里的哪个 TOKEN 吗？ 
4. WECHAT 提到 EncodingAESKey。 这个需要在程序中使用吗？ 

感谢你的建议和指导。

**Comment by smilexiaobao1992** [comment]
1.不需要开发者APPID
2.服务器地址就是你的服务器Ip或者域名（可公网访问到的）添加到你微信公众号的后台：开发者配置-回调地址
3.Token是自定义的 ，同样再开发者配置那里 ，将微信公众号（或者订阅号的）的secretkey 替换 'your_api_secret' ，后台自定义Token 替换 'your_token'  即可，第二次token = app.config['b5728cf9ec6801dedf2ec929f5ff99ec']  里面就是api_secret 同样替换掉你的就可以了。
4.不需要EncodingAESKey

**Comment by autratec** [comment]
明白了。感谢耐心答复。
    On Friday, April 21, 2023 at 02:20:47 PM GMT+8, braveguozhi.eth ***@***.***> wrote:  
 
 


1.不需要开发者APPID
2.服务器地址就是你的服务器Ip或者域名（可公网访问到的）添加到你微信公众号的后台：开发者配置-回调地址
3.Token是自定义的 ，同样再开发者配置那里 ，将微信公众号（或者订阅号的）的secretkey 替换 'your_api_secret' ，后台自定义Token 替换 'your_token' 即可，第二次token = app.config['b5728cf9ec6801dedf2ec929f5ff99ec'] 里面就是api_secret 同样替换掉你的就可以了。
4.不需要EncodingAESKey

**Comment by autratec** [comment]
Btw, 是否可以确认 第8,24,25 行是重复的？如果将 token 直接以 str 的方式写入25 行的函数是就可以了 在 第8 行的 （“ ”）内输入的 app screat key 在整个运算中有被用到吗？

**Comment by autratec** [comment]
The code works now. Thanks.
